### ISSUE TITLE
Feature Request: More math functions...

### ISSUE THREAD

**Issue by sksar** [Khan/math-input#14]
The keyboard is very limited in terms of input, there is no integration functions, matrix, determinant, and others input. 
I would like to request these features, so that any kind of mathematical equation can be typed into...

**Comment by nixterrimus** [comment]
Hey @sksar I know that this issue is from a long time ago. This is something that we're currently investigating at Khan academy. We need functions especially for geometry. We'll keep the needs in mind for even more expansion.
