### ISSUE TITLE
How can I use reactnative better

### ISSUE THREAD

**Issue by liuliu66666** [Khan/math-input#15]
I don't know how to use in reactnative .  webview?I have no better way, so I would like to consult you，thank you

**Comment by xiaokaike** [comment]
math-input  require https://github.com/mathquill/mathquill，mathquill require jQuery，so you just can use webview in RN

**Comment by kevinbarabash** [comment]
@liuliu66666 sorry there isn't a better way to use this in RN.

**Comment by liuliu66666** [comment]
@xiaokaike @kevinbarabash Thank you. I've already used the webview  in RN
