### ISSUE TITLE
Hello, how do I get the completed LaTeX encoding in the input box?

### ISSUE THREAD

**Issue by wangchao117** [Khan/math-input#18]
I use math-input in my project, it's really good for my project, but I find that my pie doesn't know how to convert the completed results into LaTeX codes. I know math-input uses mathquill, which in theory converts the completed results into LaTeX codes. Can input do that?

**Comment by thanhrossi** [comment]
@wangchao117 How do you get LateX value?

**Comment by wangchao117** [comment]
> @wangchao117 How do you get LateX value?

https://github.com/wangchao117/m-i-edit

**Comment by wangchao117** [comment]
> > @wangchao117 How do you get LateX value?
> 
> https://github.com/wangchao117/m-i-edit 
This is my math-input modified formula keyboard。

**Comment by thanhrossi** [comment]
@wangchao117  thank you so much

**Comment by wangchao117** [comment]
> so cool. But i can't understand chinese.BTW, thank you

I think you've read math-input.js carefully. In the life cycle of'componentDidUpdate', you try to output'this. mathField. getContent ()', and you'll find that it's the Latex code you entered.

**Comment by thanhrossi** [comment]
@wangchao117  thank you

**Comment by thanhrossi** [comment]
Hi @wangchao117 . I want to use this button http://prntscr.com/lwszca
But it's not working ?

**Comment by wangchao117** [comment]
> Hi @wangchao117 . I want to use this button http://prntscr.com/lwszca
> But it's not working ?

MathQuill is used to analyze LaTeX by math-input, but the analysis of MathQuill formula is not perfect. After my test, the formula can not be normally resolved.
[Please jump](https://www.jianshu.com/p/18f8d7c624c8)

**Comment by thanhrossi** [comment]
thank you @wangchao117

**Comment by wangchao117** [comment]
> @wangchao117 . I want have multiple input field. Can you help me ?

I don't quite understand what you mean. Can you describe it in detail?

**Comment by thanhrossi** [comment]
@wangchao117 here is it : https://i.imgur.com/lq6zLvz.png

**Comment by xiaokaike** [comment]
@thanhrossi  you can use this Pull Request https://github.com/mathquill/mathquill/pull/661，build your custom mathquill to replace  math-input use mathquill

**Comment by thanhrossi** [comment]
@xiaokaike thank you

**Comment by wangchao117** [comment]
> @wangchao117 here is it : https://i.imgur.com/lq6zLvz.png

I haven't considered this situation because my project doesn't have this requirement, but I think you can change the position of the input component when focusing on it. For example, when you enter the first input box, let the input move to the position of the second input box. If it is the second input box, let the input move to the position of the second input box.
In addition, Khan College's own projects have your needs, and I think you can look at the configuration.

**Comment by xiaokaike** [comment]
<img width="100" alt="image" src="https://user-images.githubusercontent.com/4251499/50282761-cfd1a180-048e-11e9-8eb7-34b54cebc5af.png">

**Comment by thanhrossi** [comment]
@wangchao117 thanks a lot for your help

**Comment by thanhrossi** [comment]
My solution is use muliple input, and concat string.

Expected string look like: 

`\begin{cases}
2x+3y=0\\
5x-5y=0\\
65x+33y=0
\end{cases}`

**Comment by wangchao117** [comment]
> > @wangchao117 here is it : https://i.imgur.com/lq6zLvz.png
> 
> I haven't considered this situation because my project doesn't have this requirement, but I think you can change the position of the input component when focusing on it. For example, when you enter the first input box, let the input move to the position of the second input box. If it is the second input box, let the input move to the position of the second input box.
> In addition, Khan College's own projects have your needs, and I think you can look at the configuration.

 [This may help you ](https://github.com/Khan/perseus)

**Comment by thanhrossi** [comment]
Hi @wangchao117 I want insert line break to input. I cant find it? Can you help me ?

**Comment by thanhrossi** [comment]
Hi @wangchao117 @xiaokaike . I'll try an try. here is it : 
`**[Keys.TWOTERM]: {str: '\\begin{cases}\\\end{cases}', fn: WRITE},**`
and result: 
http://prntscr.com/lxupwb

**Comment by thanhrossi** [comment]
Well done :http://prntscr.com/lxvj83

**Comment by wangchao117** [comment]
> Well done :http://prntscr.com/lxvj83

How did you achieve that? I use your code as if it can be parsed properly. Is there any requirement for the version of Mathquill? Can you show me your code? I find it very interesting.

**Comment by thanhrossi** [comment]
Hi @wangchao117 .
Step 1. I use Pull Request [mathquill/mathquill#661](https://github.com/dominique-unruh/mathquill/commits/cases) suggest by @xiaokaike 

`git clone --single-branch --branch cases https://github.com/dominique-unruh/mathquill.git`

Step 2.  Build mathquill . 

`To build mathquill, you will need a node.js installation.
We recommend https://github.com/visionmedia/n for installing node,
otherwise, you can get it from http://nodejs.org/ .

You will then need to update the dependencies with `npm`, like so:

    % npm install

If this installs properly, you should simply be able to run `make`,
and mathquill will be built in the `build/` directory.  Alternatively,
for development, you can run `make server`, which will automatically
re-make, and also serve the demo, the unit tests, and the visual tests.

            demo -> http://localhost:9292/test/demo.html
      unit tests -> http://localhost:9292/test/unit.html
    visual tests -> http://localhost:9292/test/visual.html

If any of this does not work, please let us know!  We want to make
hacking on mathquill as easy as possible.`

Copy all mathquill folder replace to current project.
In **math-input\src\components\input\math-wrapper.js**
Change to : 
` [Keys.TWOTERM]: {str: '\\begin{cases}\\\\\\end{cases}', fn: WRITE},`

**Comment by thanhrossi** [comment]
@wangchao117 . I want insert this icon 
http://prntscr.com/ly6688  to math-input . How did you do it ?

**Comment by wangchao117** [comment]
> @wangchao117 . I want insert this icon
> http://prntscr.com/ly6688 to math-input . How did you do it ?

I'm sorry, but I didn't find a solution. I just summarized the formulas mathquill couldn't recognize.

**Comment by wangchao117** [comment]
> Hi @wangchao117 .
> Step 1. I use Pull Request [mathquill/mathquill#661](https://github.com/dominique-unruh/mathquill/commits/cases) suggest by @xiaokaike
> 
> `git clone --single-branch --branch cases https://github.com/dominique-unruh/mathquill.git`
> 
> Step 2. Build mathquill .
> 
> `To build mathquill, you will need a node.js installation.
> We recommend https://github.com/visionmedia/n for installing node,
> otherwise, you can get it from http://nodejs.org/ .
> 
> You will then need to update the dependencies with `npm`, like so:
> 
> ```
> % npm install
> ```
> If this installs properly, you should simply be able to run `make`,
> and mathquill will be built in the `build/` directory. Alternatively,
> for development, you can run `make server`, which will automatically
> re-make, and also serve the demo, the unit tests, and the visual tests.
> 
> ```
>         demo -> http://localhost:9292/test/demo.html
>   unit tests -> http://localhost:9292/test/unit.html
> visual tests -> http://localhost:9292/test/visual.html
> ```
> If any of this does not work, please let us know! We want to make
> hacking on mathquill as easy as possible.`
> 
> Copy all mathquill folder replace to current project.
> In **math-input\src\components\input\math-wrapper.js**
> Change to :
> ` [Keys.TWOTERM]: {str: '\\begin{cases}\\\\\\end{cases}', fn: WRITE},`

nice!!!

**Comment by thanhrossi** [comment]
> I'm sorry, but I didn't find a solution. I just summarized the formulas mathquill couldn't recognize.

How do you create a new button( like  Systems of 3 Equations's button  )?
