### ISSUE TITLE
Demo doesn't work ?

### ISSUE THREAD

**Issue by thanhtungdp** [Khan/math-input#2]
Hi. I have run demo. But it doesn't work, when i'm typing ...
Image:
<img width="611" alt="screen shot 2016-06-10 at 3 20 46 pm" src="https://cloud.githubusercontent.com/assets/4653102/15958341/395da60a-2f1f-11e6-898c-1e3e5fce47ad.png">
I have turn on Console, and it not show errors, and warning

**Comment by kevinbarabash** [comment]
It only response to touch events.  Make sure that you've enable mobile "emulation" in Chrome dev tools.
