### ISSUE TITLE
Run on chrome desktop

### ISSUE THREAD

**Issue by peachdev6** [Khan/math-input#20]
Hi
Is there anyway to run it on desktop?

**Comment by mehranmd** [comment]
Hello sir.
You can use [Chocolatey](http://chocolatey.org).
install it and then use :
`choco install nodejs`
` choco install yarn`
`choco install git`
after that you can use git to obtain a copy of the code:
`git clone https://github.com/Khan/math-input.git`
`cd math-input`
`yarn install`
`yarn watch`
now open index.html with Chrome and use inspect option of chrome to simulate a phone interface.

**Comment by nixterrimus** [comment]
@peachdev6 The project, as-is, is designed to work just on mobile. But! The good news is that we're just starting on making this work on desktop and mobile. Keep your eyes on this project for updates in the future.
