### ISSUE TITLE
onClick support, and others...

### ISSUE THREAD

**Issue by f-alonso-vendrell** [Khan/math-input#7]
I have forked this and included:

* onClick support => touchStart+touchEnd , so it can be used in other browsers
* no bounded to "root" div, but divs of class="math-input"
* value (latex) accesible from hosting div vi a atribute "math-input-value"

check it at https://github.com/f-alonso-vendrell/math-input and easy demo at https://f-alonso-vendrell.github.io/math-input/

let me know if you want that included, or do PR from it

**Comment by nixterrimus** [comment]
Hey @f-alonso-vendrell we're just starting to make this input desktop-web and mobile-web compatible. I appreciate the feedback. I know this issue is from a very long time ago but I hope that if you still need something like this project that you'll benefit from the changes we're making.
